name: Publish to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - name: "app"
            # googleAnalyticsId: 'G-XXXXXXXXXX'
          - name: 'docs'
          # googleAnalyticsId: 'G-XXXXXXXXXX'

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: "npm"
      - name: Install
        run: npm ci

      - name: Run build
        run: npm run build -- --filter=${{ matrix.name }}

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: promptpro-${{ matrix.name }}
          directory: ./${{ matrix.name}}/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
