name: Publish to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_app:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: "npm"
      - name: Install
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: promptlee-prod
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  # publish_docs:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
      
  #   steps:
  #     - name: Checkout 🛎
  #       uses: actions/checkout@v3
  #     - name: Setup node env 🏗
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.13.0
  #         cache: "npm"
  #     - name: Install
  #       run: npm ci
  #       working-directory: docs

  #     - name: Run build
  #       run: npm run build
  #       working-directory: docs

  #     - name: Publish
  #       uses: cloudflare/pages-action@1
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         projectName: promptlee-docs
  #         directory: ./docs/dist
  #         gitHubToken: ${{ secrets.GITHUB_TOKEN }}
